# Use a lightweight Python image
FROM python:3.9-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
ADD dice_roll.py /app/dice_roll.py

# Make the Python script executable
RUN chmod +x /app/dice_roll.py

# Set the command to execute the Python script
CMD ["python", "./dice_roll.py"]


