FROM alpine

# Set the working directory
WORKDIR /mydir

# Add chucknorris.py to the working directory
ADD chucknorris.py /mydir

# Install Python3, pip, and curl
RUN apk add --no-cache python3 py3-pip curl

# Install the requests library using pip with the '--break-system-packages' flag
RUN pip install --break-system-packages requests

# Make the Python script executable
RUN chmod +x /mydir/chucknorris.py

# Set the command to execute the Python script
CMD ["python3", "./chucknorris.py"]
